modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="treetools"
version="1.3"
displayName="Tree Tools Mod"
description='''Several Tree tools to make creative Building Easier'''
logoFile="icon.png"